#!/usr/bin/env python3
"""Validate files this crate wrote with the specification's own reader.

`verify_vectors.py` is the corpus' independent validator: it shares no code with
the Rust crate, and its `validate()` takes any `.lumen` path. This script points it
at files generated by the crate's `make_test_file` example, so the agreement
between the two implementations is checked in the direction that a crate's own
tests cannot check - another implementation reading *our* bytes.

Run from the repository root, after generating the files:

    cargo run --manifest-path rust/lumen/Cargo.toml --example make_test_file -- /tmp
    python test-vectors/cross_check.py /tmp

Exits 0 only when both files pass every check. Requires `zstandard`,
`cryptography` and `argon2-cffi`, the same three the corpus validator needs for
its encrypted vectors.
"""

import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import verify_vectors as v  # noqa: E402


def auth_payload(raw: bytes) -> bytes:
    """The AUTH chunk's stored bytes, read straight out of the directory."""
    dir_offset, chunk_count = struct.unpack_from("<QI", raw, 8)
    for index in range(chunk_count):
        base = dir_offset + index * 32
        if raw[base:base + 4] != b"AUTH":
            continue
        offset, uncompressed, stored, _flags = struct.unpack_from("<QQQI", raw, base + 4)
        return raw[offset:offset + (stored or uncompressed)]
    raise SystemExit("no AUTH chunk")


def password_credentials(path: Path, password: str) -> dict:
    """The crypto block `verify_vectors` wants, taken from the file itself.

    The salt and the Argon2id cost parameters are whatever the encoder drew, so
    reading them back is also a check that it wrote them where a reader looks.
    """
    raw = path.read_bytes()
    auth = auth_payload(raw)
    return {
        "password_utf8": password,
        "argon2": {
            "salt": auth[20:36].hex(),
            "iterations": struct.unpack_from("<I", auth, 36)[0],
            "memory_kib": struct.unpack_from("<I", auth, 40)[0],
            "parallelism": auth[44],
        },
    }


def main() -> int:
    directory = Path(sys.argv[1] if len(sys.argv) > 1 else "target")
    cases = [
        (directory / "sample.lumen", None),
        # No LHAS: section 4.11 makes it optional and section 10.3 forbids
        # requiring an optional mechanism, so the reference reader must accept it.
        (directory / "sample-no-lhas.lumen", None),
        (directory / "sample-encrypted.lumen", "lumen-example"),
    ]

    if v.crc32c(b"123456789") != 0xE3069283:
        print("FATAL: the reference validator's CRC-32C self-test failed")
        return 2

    failed = False
    for path, password in cases:
        if not path.exists():
            print("MISSING %s - generate it with the make_test_file example" % path)
            failed = True
            continue
        crypto = password_credentials(path, password) if password else None
        checks = v.validate(str(path), strict=True, verbose=False, crypto=crypto)
        failures = checks.failed()
        state = "ok" if not failures else "FAILED"
        print("%-7s %-32s %3d checks%s" % (
            state,
            path.name,
            len(checks.items),
            "" if not failures else "  " + ", ".join(failures),
        ))
        if failures:
            failed = True
        if "__checks_complete" not in dict(checks.items):
            print("        the validator stopped early; the run is not conclusive")
            failed = True

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
